global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nutro-bot'
    static_configs:
      - targets: ['bot:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 