apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - name: "traceID"
          datasourceUid: "tempo"
    secureJsonData:
      basicAuthPassword: ""
      basicAuthUser: "" 